=== chain-registry/fixtures/registries/full/chain.schema.json
{
  "$id": "https://sikka.tech/chain.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Chain",
  "description": "Chain.json is a metadata file that contains information about a blockchain.",
  "type": "object",
  "required": [
    "chainName",
    "chainId",
    "bech32Prefix"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^(\\.\\./)+chain\\.schema\\.json$"
    },
    "website": {
      "type": "string",
      "format": "uri"
    },
    "status": {
      "enum": [
        "live",
        "upcoming",
        "killed"
      ]
    },
    "slip44": {
      "type": "number"
    },
    "fees": {
      "type": "object",
      "required": [
        "feeTokens"
      ],
      "properties": {
        "feeTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/feeToken"
          }
        }
      },
      "additionalProperties": false
    },
    "staking": {
      "type": "object",
      "required": [
        "stakingTokens"
      ],
      "properties": {
        "stakingTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/stakingToken"
          }
        },
        "lockDuration": {
          "type": "object",
          "properties": {
            "blocks": {
              "type": "number",
              "description": "The number of blocks for which the staked tokens are locked."
            },
            "time": {
              "type": "string",
              "description": "The approximate time for which the staked tokens are locked."
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "codebase": {
      "type": "object",
      "properties": {
        "binaries": {
          "type": "object",
          "properties": {
            "linux/amd64": {
              "type": "string",
              "format": "uri"
            },
            "linux/arm64": {
              "type": "string",
              "format": "uri"
            },
            "darwin/amd64": {
              "type": "string",
              "format": "uri"
            },
            "darwin/arm64": {
              "type": "string",
              "format": "uri"
            },
            "windows/amd64": {
              "type": "string",
              "format": "uri"
            },
            "windows/arm64": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "consensus": {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "tendermint",
                "cometbft",
                "sei-tendermint"
              ]
            },
            "version": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "genesis": {
          "type": "object",
          "required": [
            "genesisUrl"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "genesisUrl": {
              "type": "string",
              "format": "uri"
            },
            "icsCcvUrl": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "versions": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name"
            ],
            "properties": {
              "name": {
                "type": "string",
                "description": "Official Upgrade Name"
              },
              "tag": {
                "type": "string",
                "description": "Git Upgrade Tag"
              },
              "height": {
                "type": "number",
                "description": "Block Height"
              },
              "proposal": {
                "type": "number",
                "description": "Proposal that will officially signal community acceptance of the upgrade."
              },
              "consensus": {
                "type": "object",
                "required": [
                  "type"
                ],
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "tendermint",
                      "cometbft",
                      "sei-tendermint"
                    ]
                  },
                  "version": {
                    "type": "string"
                  }
                },
                "additionalProperties": false
              },
              "binaries": {
                "type": "object",
                "properties": {
                  "linux/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "linux/arm64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "darwin/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "darwin/arm64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "windows/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "windows/arm64": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "additionalProperties": false
              },
              "previousVersionName": {
                "type": "string",
                "description": "[Optional] Name of the previous version"
              },
              "nextVersionName": {
                "type": "string",
                "description": "[Optional] Name of the following version"
              },
              "recommendedVersion": {
                "type": "string"
              },
              "goVersion": {
                "type": "string",
                "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
                "description": "Minimum accepted go version to build the binary."
              },
              "compatibleVersions": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "cosmosSdkVersion": {
                "type": "string"
              },
              "cosmwasmVersion": {
                "type": "string"
              },
              "cosmwasmEnabled": {
                "type": "boolean"
              },
              "cosmwasmPath": {
                "type": "string",
                "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
                "pattern": "^\\$HOME.*$"
              },
              "ibcGoVersion": {
                "type": "string"
              },
              "icsEnabled": {
                "type": "array",
                "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
                "items": {
                  "type": "string",
                  "description": "IBC app or ICS standard.",
                  "enum": [
                    "ics20-1",
                    "ics27-1",
                    "mauth"
                  ]
                }
              }
            },
            "additionalProperties": false
          }
        },
        "gitRepo": {
          "type": "string",
          "format": "uri"
        },
        "recommendedVersion": {
          "type": "string"
        },
        "goVersion": {
          "type": "string",
          "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
          "description": "Minimum accepted go version to build the binary."
        },
        "compatibleVersions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cosmosSdkVersion": {
          "type": "string"
        },
        "cosmwasmVersion": {
          "type": "string"
        },
        "cosmwasmEnabled": {
          "type": "boolean"
        },
        "cosmwasmPath": {
          "type": "string",
          "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
          "pattern": "^\\$HOME.*$"
        },
        "ibcGoVersion": {
          "type": "string"
        },
        "icsEnabled": {
          "type": "array",
          "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
          "items": {
            "type": "string",
            "description": "IBC app or ICS standard.",
            "enum": [
              "ics20-1",
              "ics27-1",
              "mauth"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "png": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
          },
          "svg": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
          },
          "theme": {
            "type": "object",
            "properties": {
              "circle": {
                "type": "boolean"
              },
              "primaryColorHex": {
                "type": "string",
                "pattern": "^#[0-9a-fA-F]{6}$"
              },
              "darkMode": {
                "type": "boolean"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          },
          "layout": {
            "type": "string",
            "enum": [
              "logo",
              "logomark",
              "logotype"
            ],
            "description": "logomark == icon only; logotype == text only; logo == icon + text."
          },
          "imageSync": {
            "$ref": "#/$defs/pointer"
          },
          "textPosition": {
            "type": "string",
            "enum": [
              "top",
              "bottom",
              "left",
              "right",
              "integrated"
            ],
            "description": "Indicates in which position the text is placed, in case the layout is 'icon' type, it's required only in this case."
          }
        },
        "if": {
          "properties": {
            "layout": {
              "const": "logo"
            }
          },
          "required": [
            "layout"
          ]
        },
        "then": {
          "required": [
            "text_position"
          ]
        },
        "anyOf": [
          {
            "required": [
              "png"
            ]
          },
          {
            "required": [
              "svg"
            ]
          }
        ],
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string",
      "maxLength": 3000
    },
    "peers": {
      "type": "object",
      "properties": {
        "seeds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/peer"
          }
        },
        "persistentPeers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/peer"
          }
        }
      },
      "additionalProperties": false
    },
    "apis": {
      "type": "object",
      "properties": {
        "rpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "rest": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "wss": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpcWeb": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "evmHttpJsonrpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        }
      },
      "additionalProperties": false
    },
    "explorers": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/explorer"
      }
    },
    "keywords": {
      "type": "array",
      "maxContains": 20,
      "items": {
        "type": "string"
      }
    },
    "chainName": {
      "type": "string",
      "pattern": "[a-z0-9]+"
    },
    "chainId": {
      "type": "string"
    },
    "preForkChainName": {
      "type": "string",
      "pattern": "[a-z0-9]+"
    },
    "prettyName": {
      "type": "string"
    },
    "updateLink": {
      "type": "string",
      "format": "uri"
    },
    "networkType": {
      "enum": [
        "mainnet",
        "testnet",
        "devnet"
      ]
    },
    "bech32Prefix": {
      "type": "string",
      "description": "The default prefix for the human-readable part of addresses that identifies the coin type. Must be registered with SLIP-0173. E.g., 'cosmos'"
    },
    "bech32Config": {
      "type": "object",
      "description": "Used to override the bech32_prefix for specific uses.",
      "properties": {
        "bech32PrefixAccAddr": {
          "type": "string",
          "description": "e.g., 'cosmos'"
        },
        "bech32PrefixAccPub": {
          "type": "string",
          "description": "e.g., 'cosmospub'"
        },
        "bech32PrefixValAddr": {
          "type": "string",
          "description": "e.g., 'cosmosvaloper'"
        },
        "bech32PrefixValPub": {
          "type": "string",
          "description": "e.g., 'cosmosvaloperpub'"
        },
        "bech32PrefixConsAddr": {
          "type": "string",
          "description": "e.g., 'cosmosvalcons'"
        },
        "bech32PrefixConsPub": {
          "type": "string",
          "description": "e.g., 'cosmosvalconspub'"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "daemonName": {
      "type": "string"
    },
    "nodeHome": {
      "type": "string"
    },
    "keyAlgos": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "secp256k1",
          "ethsecp256k1",
          "ed25519",
          "sr25519",
          "bn254"
        ],
        "uniqueItems": true
      }
    },
    "alternativeSlip44s": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "logoURIs": {
      "type": "object",
      "properties": {
        "png": {
          "type": "string",
          "format": "uri-reference",
          "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
        },
        "svg": {
          "type": "string",
          "format": "uri-reference",
          "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
        }
      },
      "additionalProperties": false
    },
    "extraCodecs": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ethermint",
          "injective"
        ],
        "uniqueItems": true
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "peer": {
      "type": "object",
      "required": [
        "id",
        "address"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "endpoint": {
      "type": "object",
      "required": [
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "archive": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "explorer": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "txPage": {
          "type": "string"
        },
        "accountPage": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "pointer": {
      "type": "object",
      "description": "The (primary) key used to identify an object within the Chain Registry.",
      "required": [
        "chainName"
      ],
      "properties": {
        "chainName": {
          "type": "string",
          "description": "The chain name or platform from which the object resides. E.g., 'cosmoshub', 'ethereum', 'forex', or 'nasdaq'"
        },
        "baseDenom": {
          "type": "string",
          "description": "The base denom of the asset from which the object originates. E.g., when describing ATOM from Cosmos Hub, specify 'uatom', NOT 'atom' nor 'ATOM'; base units are unique per platform."
        }
      },
      "additionalProperties": false
    },
    "feeToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        },
        "fixedMinGasPrice": {
          "type": "number"
        },
        "lowGasPrice": {
          "type": "number"
        },
        "averageGasPrice": {
          "type": "number"
        },
        "highGasPrice": {
          "type": "number"
        },
        "gasCosts": {
          "type": "object",
          "properties": {
            "cosmosSend": {
              "type": "number"
            },
            "ibcTransfer": {
              "type": "number"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "stakingToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}

=== chain-registry/fixtures/registries/minimal/decentr/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "decentr",
  "networkType": "mainnet",
  "prettyName": "Decentr",
  "chainId": "mainnet-3",
  "bech32Prefix": "decentr",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "udec",
        "fixedMinGasPrice": 0.025,
        "lowGasPrice": 0.025,
        "averageGasPrice": 0.025,
        "highGasPrice": 0.025
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "udec"
      }
    ]
  },
  "codebase": {

  },
  "apis": {
    "rpc": [
      {
        "address": "https://poseidon.mainnet.decentr.xyz"
      },
      {
        "address": "https://rpc.decentr.chaintools.tech/"
      },
      {
        "address": "https://decentr.rpc.m.stavr.tech:443"
      },
      {
        "address": "https://decentr-rpc.ibs.team/"
      },
      {
        "address": "https://rpc-dcntr.nodine.id/"
      },
      {
        "address": "https://rpc-decentr.mms.team/"
      }
    ],
    "rest": [
      {
        "address": "https://rest.mainnet.decentr.xyz"
      },
      {
        "address": "https://decentr.api.m.stavr.tech"
      },
      {
        "address": "https://api.decentr.chaintools.tech/"
      },
      {
        "address": "https://decentr-api.ibs.team/"
      }
    ],
    "grpc": [
      {
        "address": "https://grpc-decentr.sxlzptprjkt.xyz:443"
      },
      {
        "address": "decentr.grpc.m.stavr.tech:2060"
      },
      {
        "address": "https://grpc.decentr.hexnodes.co"
      },
      {
        "address": "https://grpc.decentr.nodexcapital.com:443"
      },
      {
        "address": "grpc-decentr.mms.team:443"
      }
    ]
  },
  "explorers": [
    {
      "kind": "decentr.net",
      "url": "https://explorer.decentr.net",
      "txPage": "https://explorer.decentr.net/transactions/${txHash}?networkId=mainnet"
    },
    {
      "kind": "ping.pub",
      "url": "https://ping.pub/decentr/",
      "txPage": "https://ping.pub/decentr/tx/${txHash}"
    },
    {
      "kind": "ðŸ”¥STAVRðŸ”¥",
      "url": "https://explorer.stavr.tech/Decentr-Mainnet",
      "txPage": "https://explorer.stavr.tech/Decentr-Mainnet/tx/${txHash}"
    },
    {
      "kind": "atomscan",
      "url": "https://atomscan.com/decentr",
      "txPage": "https://atomscan.com/decentr/transactions/${txHash}",
      "accountPage": "https://atomscan.com/decentr/accounts/${accountAddress}"
    },
    {
      "kind": "Nodine.ID",
      "url": "https://explorer.co.id/decentr",
      "txPage": "https://explorer.co.id/decentr/tx/${txHash}"
    },
    {
      "kind": "THE EXPLORER",
      "url": "https://explorer.sxlzptprjkt.xyz/decentr",
      "txPage": "https://explorer.sxlzptprjkt.xyz/decentr/tx/${txHash}"
    },
    {
      "kind": "hexskrt EXPLORER",
      "url": "https://explorer.hexskrt.net/decentr",
      "txPage": "https://explorer.hexskrt.net/decentr/tx/${txHash}"
    },
    {
      "kind": "NODEXPLORER",
      "url": "https://explorer.nodexcapital.com/decentr",
      "txPage": "https://explorer.nodexcapital.com/decentr/tx/${txHash}"
    },
    {
      "kind": "Explorer ComunityNode",
      "url": "https://explorer.comunitynode.my.id/decentr",
      "txPage": "https://explorer.comunitynode.my.id/decentr/tx/${txHash}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/decentr/images/dec.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/decentr/images/dec.svg"
    }
  ]
}

=== chain-registry/fixtures/registries/minimal/andromeda/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "andromeda",
  "chainId": "andromeda-1",
  "prettyName": "Andromeda",
  "networkType": "mainnet",
  "bech32Prefix": "andr",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "uandr"
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uandr"
      }
    ],
    "lockDuration": {
      "time": "1814400s"
    }
  },
  "codebase": {
    "cosmosSdkVersion": "v0.47.8",
    "ibcGoVersion": "v7.4.0",
    "cosmwasmVersion": "v0.41.0",
    "cosmwasmEnabled": true
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.andromeda-1.andromeda.aviaone.com"
      },
      {
        "address": "https://andromeda.rpc.kjnodes.com"
      },
      {
        "address": "https://andromeda.rpc.nodex.one"
      },
      {
        "address": "https://andro.rpc.m.stavr.tech/"
      },
      {
        "address": "https://andromeda-rpc.lavenderfive.com:443"
      },
      {
        "address": "https://andromeda-mainnet-rpc.autostake.com:443"
      },
      {
        "address": "https://andromeda-rpc.stake-town.com:443"
      },
      {
        "address": "https://andromeda-rpc.stakerhouse.com:443"
      },
      {
        "address": "https://andromeda-rpc.highstakes.ch"
      },
      {
        "address": "https://andromeda-rpc.genznodes.dev"
      },
      {
        "address": "https://andromeda.rpc.kjnodes.com"
      },
      {
        "address": "andromeda-rpc.noders.services"
      },
      {
        "address": "rpc-andromeda.blockval.io"
      },
      {
        "address": "https://andromeda.rpc.liveraven.net"
      }
    ],
    "rest": [
      {
        "address": "https://api.andromeda-1.andromeda.aviaone.com/"
      },
      {
        "address": "https://andromeda.api.kjnodes.com"
      },
      {
        "address": "https://andromeda.api.nodex.one"
      },
      {
        "address": "https://andro.api.m.stavr.tech"
      },
      {
        "address": "https://andromeda-api.lavenderfive.com:443"
      },
      {
        "address": "https://andromeda-mainnet-lcd.autostake.com:443"
      },
      {
        "address": "https://andromeda-api.stake-town.com:443"
      },
      {
        "address": "https://andromeda-rest.stakerhouse.com:443"
      },
      {
        "address": "https://andromeda-api.highstakes.ch"
      },
      {
        "address": "https://andromeda-api.genznodes.dev"
      },
      {
        "address": "https://andromeda.api.kjnodes.com"
      },
      {
        "address": "andromeda-api.noders.services"
      },
      {
        "address": "api-andromeda.blockval.io"
      },
      {
        "address": "https://andromeda.api.liveraven.net"
      }
    ],
    "grpc": [
      {
        "address": "andromeda-grpc.lavenderfive.com:443"
      },
      {
        "address": "https://grpc.andromeda-1.andromeda.aviaone.com:9094"
      },
      {
        "address": "andromeda.grpc.kjnodes.com:443"
      },
      {
        "address": "andromeda-mainnet-grpc.autostake.com:443"
      },
      {
        "address": "https://andromeda.grpc.nodex.one:443"
      },
      {
        "address": "http://andromedad.grpc.t.stavr.tech:132"
      },
      {
        "address": "andromeda-grpc.stake-town.com:443"
      },
      {
        "address": "andromeda-grpc.stakerhouse.com:443"
      },
      {
        "address": "andromeda-grpc.genznodes.dev:27090"
      },
      {
        "address": "andromeda.grpc.kjnodes.com:443"
      },
      {
        "address": "andromeda-grpc.noders.services:34090"
      },
      {
        "address": "grpc-andromeda.blockval.io:443"
      },
      {
        "address": "andromeda.grpc.liveraven.net:443"
      }
    ]
  },
  "explorers": [
    {
      "kind": "ðŸ”¥STAVRðŸ”¥ Explorer",
      "url": "https://explorer.stavr.tech/Andromeda-Mainnet",
      "txPage": "https://explorer.stavr.tech/Andromeda-Mainnet/tx/${txHash}",
      "accountPage": "https://explorer.stavr.tech/Andromeda-Mainnet/account/${accountAddress}"
    },
    {
      "kind": "exploreme.pro",
      "url": "https://andromeda.exploreme.pro",
      "txPage": "https://andromeda.exploreme.pro/transaction/${txHash}",
      "accountPage": "https://andromeda.exploreme.pro/account/${accountAddress}"
    },
    {
      "kind": "Cosmotracker",
      "url": "https://cosmotracker.com/andromeda",
      "txPage": "https://cosmotracker.com/andromeda/tx/${txHash}",
      "accountPage": "https://cosmotracker.com/andromeda/account/${accountAddress}"
    },
    {
      "kind": "ping.pub",
      "url": "https://ping.pub/andromeda",
      "txPage": "https://ping.pub/andromeda/tx/${txHash}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/andromeda/images/andromeda-logo.png"
    }
  ]
}

=== chain-registry/fixtures/registries/minimal/arkh/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "arkh",
  "networkType": "mainnet",
  "website": "https://arkhadian.com/",
  "prettyName": "Arkhadian",
  "chainId": "arkh",
  "bech32Prefix": "arkh",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "arkh",
        "fixedMinGasPrice": 0.01,
        "lowGasPrice": 0.01,
        "averageGasPrice": 0.025,
        "highGasPrice": 0.03
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "arkh"
      }
    ]
  },
  "codebase": {

  },
  "apis": {
    "rpc": [
      {
        "address": "https://asc-dataseed.arkhadian.com/"
      },
      {
        "address": "https://arkh_mainnet_rpc.chain.whenmoonwhenlambo.money"
      }
    ],
    "rest": [
      {
        "address": "https://asc-blockchain-api.arkhadian.com/"
      },
      {
        "address": "https://arkh_mainnet_api.chain.whenmoonwhenlambo.money"
      }
    ],
    "grpc": [
      {
        "address": "grpc.arkh.nodestake.top:443"
      },
      {
        "address": "https://grpc.arkh.nodexcapital.com:443"
      }
    ]
  },
  "explorers": [
    {
      "kind": "NodeStake Explorer",
      "url": "https://explorer.nodestake.top/arkh",
      "txPage": "https://explorer.nodestake.top/arkh/tx/${txHash}"
    },
    {
      "kind": "Kynraze Explorer",
      "url": "https://explorer.kynraze.com/arkhadian",
      "txPage": "https://explorer.kynraze.com/arkhadian/tx/${txHash}"
    },
    {
      "kind": "NODEXPLORER",
      "url": "https://explorer.nodexcapital.com/arkhadian",
      "txPage": "https://explorer.nodexcapital.com/arkhadian/tx/${txHash}"
    },
    {
      "kind": "ðŸš€ WHEN MOON ðŸŒ• WHEN LAMBO ðŸ”¥",
      "url": "https://explorer.whenmoonwhenlambo.money/arkhadian",
      "txPage": "https://explorer.whenmoonwhenlambo.money/arkhadian/tx/${txHash}",
      "accountPage": "https://explorer.whenmoonwhenlambo.money/arkhadian/account/${accountAddress}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/arkh/images/arkh.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/arkh/images/arkh.svg"
    }
  ]
}
